### PR TITLE
Jam first

### PR DESCRIPTION
**Pull request by HalcyonVagabond**
Hello! 

Parks select feature functionality, submits to DOM. Created a scripts div in index for organizational purposes. 

git checkout master
git pull
git checkout JAM-first

### CODE REVIEW

**Comment by HalcyonVagabond** [comment]
changed scripts in index

**Comment by kurtkrafft1** [comment]
👍

**Review by kurtkrafft1 — APPROVED** [review]
Just gotta change the SRC and add container resets

**Review by tyler-simeone — APPROVED** [review]
Looks good!

**Pull request merged**
